services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgresAC
      POSTGRES_PASSWORD: AC_NT15
      POSTGRES_DB: note_taking
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql